exports.players=[
{label:"Timestamp",value:"updatedAt"},
{label:"Name",value:"lastname"},
{label:"Name",value:"firstname"},
{label:"#",value:"team.jersey_number"},
{label:"Position",value:"team.position"},
{label:"Email",value:"contact.email"},
{label:"Phone",value:"contact.phone1"},
{label:"Age",value:"public_data.age"},
{label:"Height",value:"public_data.height"},
{label:"Weight",value:"public_data.weight"},
{label:"Hometown",value:"background.hometown"},
{label:"Shooting Hand",value:"team.shooting_hand"},
{label:"Shirt size",value:"apparel.shirt"},
{label:"Sock size",value:"apparel.socks"},
{label:"Jacket size",value:"apparel.jacket"},
{label:"Hat size",value:"apparel.hat"},
{label:"Polo size",value:"apparel.polo"},
{label:"Shorts size",value:"apparel.shorts"},
{label:"Jersey size",value:"apparel.jersey"},
{label:"Headshot",value:"headshot"},
{label:"Paid",value:"paid"}
]

exports.coaches=[
{label:"First Name",value:"firstname"},
{label:"Last Name",value:"lastname"},
{label:"Position",value:"team.role"},
{label:"Email",value:"contact.email"},
{label:"Phone",value:"contact.phone1"},
{label:"Height",value:"public_data.hometown"},
{label:"Shirt size",value:"apparel.shirt"},
{label:"Sock size",value:"apparel.socks"},
{label:"Jacket size",value:"apparel.jacket"},
{label:"Hat size",value:"apparel.hat"},
{label:"Polo size",value:"apparel.polo"},
{label:"Shorts size",value:"apparel.shorts"},
{label:"Bag",value:"N/a"},
{label:"Headshot",value:"N/a"}
]
