exports.googleSpreadsheet=function(data){
return {"Time Stamp":data["updatedAt"],
 "First Name":data["firstname"],
 "Last Name":data["lastname"],
 "Email":data["contact"]["email"],
 "Alt Email":data["contact"]["alt_email"],
 "Phone":data["contact"]["phone1"],
 "Alt Phone":data["contact"]["phone2"],
 "Passport":data["contact"]["passport"],
 "Passport Exp":data["contact"]["passport_expiration"],
 "Hometown":data["background"]["hometown"],
 "Team applying for":data["background"]["team_applying_for"],
 "Highest level coached":data["background"]["highest_level_coached"],
 "Former Positions":data["background"]["former_coaching_positions"],
 "Prefered Coaching Pos":data["background"]["preferred_coaching_position"],
 "Facebook":data["contact"]["social_media"]["facebook"],
 "Instagram":data["contact"]["social_media"]["instagram"],
 "Twitter":data["contact"]["social_media"]["twitter"],
 "Linkedin":data["contact"]["social_media"]["linkedin"],
 "Shirt size":data["apparel"]["shirt"],
 "Jacket size":data["apparel"]["jacket"],
 "Hat size":data["apparel"]["hat"],
 "Polo size":data["apparel"]["polo"],
 "Preparation":data["background"]["short_answers"]["preparation"],
 "Coaching Style":data["background"]["short_answers"]["coaching_style"],
 "Why am I a good candidate":data["background"]["short_answers"]["why_a_good_candidate"],
 "Creating a team atmosphere":data["background"]["short_answers"]["create_team_atmosphere"]}
}

exports.json2csv=[
	{label:"Time Stamp",value:"updatedAt"},
	{label:"First Name",value:"firstname"},
	{label:"Last Name",value:"lastname"},
	{label:"Email",value:"contact.email"},
	{label:"Alt Email",value:"contact.alt_email"},
	{label:"Phone",value:"contact.phone1"},
	{label:"Alt Phone",value:"contact.phone2"},
	{label:"Passport",value:"contact.passport"},
	{label:"Passport Exp",value:"contact.passport_expiration"},
	{label:"Hometown",value:"background.hometown"},
	{label:"Team applying for",value:"background.team_applying_for"},
	{label:"Highest level coached",value:"background.highest_level_coached"},
	{label:"Former Positions",value:"background.former_coaching_positions"},
	{label:"Prefered Coaching Pos",value:"background.preferred_coaching_position"},
	{label:"Facebook",value:"contact.social_media.facebook"},
	{label:"Instagram",value:"contact.social_media.instagram"},
	{label:"Twitter",value:"contact.social_media.twitter"},
	{label:"Linkedin",value:"contact.social_media.linkedin"},
	{label:"Shirt size",value:"apparel.shirt"},
	{label:"Jacket size",value:"apparel.jacket"},
	{label:"Hat size",value:"apparel.hat"},
	{label:"Polo size",value:"apparel.polo"},
	{label:"Jersey size",value:"apparel.jersey"},
	{label:"Preparation",value:"background.short_answers.preparation"},
	{label:"Coaching Style",value:"background.short_answers.coaching_style"},
	{label:"Why am I a good candidate",value:"background.short_answers.why_a_good_candidate"},
	{label:"Creating a team atmosphere",value:"background.short_answers.create_team_atmosphere"}
]
