exports.googleSpreadsheet=function(data){
	return{"Time Stamp":data["updatedAt"],
	"First Name":data["firstname"],
	"Last Name":data["lastname"],
	"Birthday":data["public_data"]["date_of_birth"],
	"Gender":data["public_data"]["gender"],
	"Weight":data["public_data"]["weight"],
	"Height":data["public_data"]["height"],
	"Email":data["contact"]["email"],	
	"Alt Email":data["contact"]["alt_email"],
	"Phone":data["contact"]["phone1"],
	"Alt Phone":data["contact"]["phone2"],
	"Passport":data["contact"]["passport"],
	"Passport Exp":data["contact"]["passport_expiration"],
	"street":data["contact"]["private_data"]["address"]["street"],
	"City":data["contact"]["private_data"]["address"]["city"],
	"State":data["contact"]["private_data"]["address"]["state"],
	"Zipcode":data["contact"]["private_data"]["address"]["zipcode"],
	"Parent or Guardian Name":data["contact"]["private_data"]["guardian_name"],
	"Parent or Guardian Number":data["contact"]["private_data"]["guardian_number"],
	"Team trying out for":data["hockey_info"]["team"],	
	"Position":data["hockey_info"]["position"],
	"Shooting Hand":data["hockey_info"]["shooting_hand"],
	"Tournament Team":data["hockey_info"]["tournament_team"],
	"League Team":data["hockey_info"]["league_team"],	
	"Website":data["hockey_info"]["website"],	
	"Jersey Number 1st choice":data["hockey_info"]["jersey_number"]["choice1"],		
	"Jersey Number 2nd choice":data["hockey_info"]["jersey_number"]["choice2"],
	"Jersey Number 3rd choice":data["hockey_info"]["jersey_number"]["choice3"],	
	"Shirt size":data["apparel"]["shirt"],	
	"Sock size":data["apparel"]["socks"],	
	"Jacket size":data["apparel"]["jacket"],		
	"Hat size":data["apparel"]["hat"],
	"Polo size":data["apparel"]["polo"],	
	"Shorts size":data["apparel"]["shorts"],	
	"Jersey size":data["apparel"]["jersey"],
	"Education":data["background"]["education"],	
	"Hometown":data["public_data"]["hometown"],	
	"Hockey History":data["background"]["hockey_history"],	
	"Other sports played":data["background"]["other_sports"],	
	"Career highlights":data["background"]["career_highlights"],	
	"Facebook":data["contact"]["social_media"]["facebook"],	
	"Instagram":data["contact"]["social_media"]["instagram"],	
	"Twitter":data["contact"]["social_media"]["twitter"],	
	"Linkedin":data["contact"]["social_media"]["linkedin"],	
	"Favorite Movie":data["favorite"]["movie"],	
	"Favorite TV show":data["favorite"]["tv_show"],	
	"Favorite Athlete":data["favorite"]["athlete"],	
	"Favorite sport not hockey":data["favorite"]["other_sport"],	
	"Favorite food or restaurant":data["favorite"]["food_or_restaurant"]
}
}

exports.json2csv=[
{label:"Time Stamp",value:"updatedAt"},
{label:"First Name",value:"firstname"},
{label:"Last Name",value:"lastname"},
{label:"Birthday",value:"public_data.date_of_birth"},
{label:"Gender",value:"public_data.gender"},
{label:"Weight",value:"public_data.weight"},
{label:"Height",value:"public_data.height"},
{label:"Email",value:"contact.email"},
{label:"Alt Email",value:"contact.alt_email"},
{label:"Phone",value:"contact.phone1"},
{label:"Alt Phone",value:"contact.phone2"},
{label:"Passport",value:"contact.passport"},
{label:"Passport Exp",value:"contact.passport_expiration"},
{label:"street",value:"contact.private_data.address.street"},
{label:"City",value:"contact.private_data.address.city"},
{label:"State",value:"contact.private_data.address.state"},
{label:"Zipcode",value:"contact.private_data.address.zipcode"},
{label:"Parent/Guardian Name",value:"contact.private_data.guardian_name"},
{label:"Parent/Guardian Name",value:"contact.private_data.guardian_number"},
{label:"Team trying out for",value:"hockey_info.team"},
{label:"Position",value:"hockey_info.position"},
{label:"Shooting Hand",value:"hockey_info.shooting_hand"},
{label:"Tournament Team",value:"hockey_info.tournament_team"},
{label:"League Team",value:"hockey_info.league_team"},
{label:"Website",value:"hockey_info.website"},
{label:"Jersey Number 1st choice",value:"hockey_info.jersey_number.choice1"},
{label:"Jersey Number 2nd choice",value:"hockey_info.jersey_number.choice2"},
{label:"Jersey Number 3rd choice",value:"hockey_info.jersey_number.choice3"},
{label:"Shirt size",value:"apparel.shirt"},
{label:"Sock size",value:"apparel.socks"},
{label:"Jacket size",value:"apparel.jacket"},
{label:"Hat size",value:"apparel.hat"},
{label:"Polo size",value:"apparel.polo"},
{label:"Shorts size",value:"apparel.shorts"},
{label:"Jersey size",value:"apparel.jersey"},
{label:"Education",value:"background.education"},
{label:"Hometown",value:"background.hometown"},
{label:"Hockey History",value:"background.hockey_history"},
{label:"Other sports played",value:"background.other_sports"},
{label:"Career highlights",value:"background.career_highlights"},
{label:"Facebook",value:"contact.social_media.facebook"},
{label:"Instagram",value:"contact.social_media.instagram"},
{label:"Twitter",value:"contact.social_media.twitter"},
{label:"Linkedin",value:"contact.social_media.linkedin"},
{label:"Favorite Movie",value:"favorite.movie"},
{label:"Favorite TV show",value:"favorite.tv_show"},
{label:"Favorite Athlete",value:"favorite.athlete"},
{label:"Favorite sport (not hockey)",value:"favorite.other_sport"},
{label:"Favorite food/restaurant",value:"favorite.food_or_restaurant"}
]