exports.googleSpreadsheet=function(data){
	return{"Time Stamp":data["updatedAt"],
	"First Name":data["firstname"],
	"Last Name":data["lastname"],
	"Birthday":data["public_data"]["date_of_birth"],
	"Gender":data["public_data"]["gender"],
	"Weight":data["public_data"]["weight"],
	"Height":data["public_data"]["height"],
	"Email":data["contact"]["email"],	
	"Alt Email":data["contact"]["alt_email"],
	"Phone":data["contact"]["phone1"],
	"Alt Phone":data["contact"]["phone2"],
	"Passport":data["contact"]["passport"],
	"Passport Exp":data["contact"]["passport_expiration"],
	"street":data["contact"]["private_data"]["address"]["street"],
	"City":data["contact"]["private_data"]["address"]["city"],
	"State":data["contact"]["private_data"]["address"]["state"],
	"Zipcode":data["contact"]["private_data"]["address"]["zipcode"],
	"Parent or Guardian Name":data["contact"]["private_data"]["guardian_name"],
	"Parent or Guardian Number":data["contact"]["private_data"]["guardian_number"],
	"Last Team Played on":data["team"]["name"],
	"Jersey Number":data["team"]["jersey_number"],	
	"Position":data["team"]["position"],
	"Shooting Hand":data["team"]["shooting_hand"],	
	"Shirt size":data["apparel"]["shirt"],	
	"Sock size":data["apparel"]["socks"],	
	"Jacket size":data["apparel"]["jacket"],		
	"Hat size":data["apparel"]["hat"],
	"Polo size":data["apparel"]["polo"],	
	"Shorts size":data["apparel"]["shorts"],	
	"Jersey size":data["apparel"]["jersey"],
	"Education":data["background"]["education"],	
	"Hometown":data["public_data"]["hometown"],	
	"Facebook":data["contact"]["social_media"]["facebook"],	
	"Instagram":data["contact"]["social_media"]["instagram"],	
	"Twitter":data["contact"]["social_media"]["twitter"],	
	"Linkedin":data["contact"]["social_media"]["linkedin"],	
}
}